version: '3.9'

services:
  db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bussinessv3
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/api
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bcai?schema=public
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  pgdata:
